### ISSUE TITLE
Enlace: admins do not have access to all participants

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/lisc-ttm#155]
@kevinrak9 reports:

>When trying to delete duplicate participants from the system, I initially got a message saying I did not have access to the participant's profile because they were not associated with any program I had access to. This is despite being an admin user, which should have access to all participants. 

I think I understand why this is happening, and it has to do with the #121 changes.  I suspect that we need to be sure to automatically grant admin users access to new programs that are created.  It might be a little more complicated, though.  I'll comment here when I know what's going on.

**Comment by cecilia-donnelly** [comment]
I think this is the correct diagnosis.  We will also need to update the current admin users with access to all programs (I think there's one program that they don't have access to at the moment).

@kevinrak9, does that sound right to you?  That is, did you (improperly) not have access to the whole program?  Or was it a separate problem in that you had access to the program but not the specific participant?

**Comment by kevinrak9** [comment]
@cecilia-donnelly Sorry, I missed this comment...I think it's partially right. I have had to add access for myself to newly created programs, so (what seems to have happened in the commit 01b5cf3) of automatically granting access helps. Thanks! 

However, there is a situation where an admin user would not have access to a participant because they are not associated with a program. On the attached screenshot, I was not able to access the profile of "test access," which I had created but not linked to a program. But, I was able to delete that profile. So, the main issue of not being able to delete participants appears resolved, and what remains is probably low priority. 
[test access screenshot 2015-12-15.pdf](https://github.com/OpenTechStrategies/lisc-ttm/files/63224/test.access.screenshot.2015-12-15.pdf)

**Comment by cecilia-donnelly** [comment]
@kevinrak9 yes, I see what you mean.  If you think it's low priority then it is!  I'm guessing that most participants are created for a specific session, so the issue of not having access to a participant without a program would be pretty rare.  If that's true then we can leave it be until it becomes an issue for you.

**Comment by kevinrak9** [comment]
In the mirror site, my admin account can access 
TEST_1_2016	Our Lady of Tepeyac Elementary School	
and
TEST_2_2016	Farragut High School
right away. My data entry user account cannot, so it seems to be working correctly. Thanks!

**Comment by cecilia-donnelly** [comment]
Deployed on [2016-01-14].
