### ISSUE TITLE
Updating attendance information fails to save.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/lisc-ttm#163]
@kevinrak9 reports this bug:

> I've run into a weird issue with attendance. Apparently, data entry users have been updating attendance, but it has not been saving properly.
> 
> It seems the first time they edit attendance, it saves correctly (see screenshot 1 for initial, screenshot 2 for edit, and screenshot 3 for after refreshing). But, after this, it doesn't save correctly (screenshot 4 for edit, and screenshot 5 for after refreshing, which has reverted to the previous version).
> 
> It could be something else, but that is my best guess for what's happening. If you could look into this soon, that would be a huge help.

Screenshots included here because they show no confidential data (thanks, Kevin!).  Each screenshot was originally a 2-page PDF; I've converted them to PNG files here, because for some reason GitHub isn't allowing the PDF to upload even though the error message claims that PDF is a supported type, so it's *two* PNG files per screenshot.

**Screenshot 1:**

![attendance-screenshot-01-20160129-p0](https://cloud.githubusercontent.com/assets/401111/12688300/ebf47d18-c69a-11e5-8fb4-d4546402c219.png)
![attendance-screenshot-01-20160129-p1](https://cloud.githubusercontent.com/assets/401111/12688298/ebee42ea-c69a-11e5-9b05-a4898390c0f9.png)

**Screenshot 2:**

![attendance-screenshot-02-20160129-p0](https://cloud.githubusercontent.com/assets/401111/12688297/ebed6e56-c69a-11e5-9bb9-9f9247870cbd.png)
![attendance-screenshot-02-20160129-p1](https://cloud.githubusercontent.com/assets/401111/12688295/ebeb2e3e-c69a-11e5-9a0b-b2e08563c23a.png)

**Screenshot 3:**

![attendance-screenshot-03-20160129-p0](https://cloud.githubusercontent.com/assets/401111/12688296/ebecdd2e-c69a-11e5-91ca-733e633f396d.png)
![attendance-screenshot-03-20160129-p1](https://cloud.githubusercontent.com/assets/401111/12688299/ebeea212-c69a-11e5-977b-027765981787.png)

**Screenshot 4:**

![attendance-screenshot-04-20160129-p0](https://cloud.githubusercontent.com/assets/401111/12688293/ebdff730-c69a-11e5-9c5f-6d2f26516036.png)
![attendance-screenshot-04-20160129-p1](https://cloud.githubusercontent.com/assets/401111/12688294/ebe59816-c69a-11e5-803c-11ed241ce4be.png)

**Screenshot 5:**

![attendance-screenshot-05-20160129-p0](https://cloud.githubusercontent.com/assets/401111/12688292/ebd180ba-c69a-11e5-96af-bff4f24796eb.png)
![attendance-screenshot-05-20160129-p1](https://cloud.githubusercontent.com/assets/401111/12688291/ebc509ac-c69a-11e5-8575-6194b32c21e4.png)

**Comment by cecilia-donnelly** [comment]
Data entry users are having this issue.  I suspect this has to do with the #78 changes, in which we added additional permission checks.  The bug occurs when a participant is first marked absent for a date and then marked present again.  In order to undo an absence for a person on a date, the system deletes the record of that absence (from the `Absences` table).  Data entry users, however, do not have rights to delete records from the database.  Therefore, when a data entry user marks someone absent by mistake and attempts to mark them as present again, they can't delete the record of the absence so (apparently??!) the mark-as-present action fails silently.

I believe that I just need to allow data entry users to remove absences (aka, mark someone present again).
